### ISSUE TITLE
Clone trait on Enumerator doesn’t really clone it

### ISSUE THREAD

**Issue by Hawk777** [Smithay/udev-rs#10]
The `Enumerator` class implements the `Clone` trait, but it doesn’t really clone the enumerator. My impression (and this could be wrong) of Rust objects is that they ought to act like values, so cloning something ought to give you an identical thing that is independent of the original. However, `Enumerator` doesn’t do this. Consider the following code:

```rust
fn main() {
	let mut en1 = udev::Enumerator::new().unwrap();
	let mut en2 = en1.clone();
	en1.match_subsystem("hidraw").unwrap();
	en2.match_subsystem("usb").unwrap();
	for dev in en1.scan_devices().unwrap() {
		println!("Found a hidraw at {:?}", dev.devnode());
	}
	for dev in en2.scan_devices().unwrap() {
		println!("Found a usb at {:?}", dev.devnode());
	}
}
```

This will print all the hidraw devices *and* all the USB devices in *both* loops. That’s because `en1` and `en2` aren’t really clones, they’re wrappers around pointers to the same underlying enumerator. So both subsystem filters affect “both” enumerators, and both `scan_devices` calls find both sets of devices.

Given that `Enumerator` is mutable, cloning it via reference counting seems like unexpected behaviour from an idiomatic-Rust perspective, I think.

**Comment by Drakulix** [comment]
Yes, it is not really ergonomic to have mutable ref-counting objects. But the underlying udev api has no way to actually copy the `Enumerator`. It has however reference-counting functions. (I did not introduce these semantics).

So the only way to make this "more" ergonomic, would be to remove the clone implementation. I am not a huge fan of that.

Because the whole libraries is just a thin-wrapper around a C-api and I do not plan on changing this, I am going to close this issue.

Feel free to reopen, if you have a better idea how to tackle this.

**Comment by Hawk777** [comment]
Yeah, I don’t have a great answer. All I thought of was making it uncloneable, or maybe renaming it to something like `EnumeratorRef` (because an object of type `Enumerator` isn’t an enumerator, it’s a reference to an enumerator). But maybe you don’t want to break compatibility for such a trivial reason. I’m fine with leaving it alone.
